### ISSUE TITLE
Can't read json schemas from classpath

### ISSUE THREAD

**Issue by jhhdk** [jsonschema2dataclass/js2d-gradle#12]
Suppose i have a schema with definitions in jar and I want to generate classes from a schema that uses those definitions.
That doesn't seem to work with gradle plugin (this or the deprecated one), but it works fine in maven.
[test.zip](https://github.com/eirnym/js2p-gradle/files/5708267/test.zip)

**Comment by eirnym** [comment]
Thank you for a proposition, I'll see what I can do for it
