### ISSUE TITLE
Strange behaviour on publishing a release

### ISSUE THREAD

**Issue by eirnym** [jsonschema2dataclass/js2d-gradle#133]
Release 3.1.0 has bot been published properly

**Comment by sergejkv** [comment]
Hi, any updates on this? 3.1.0 is still not available on gradle plugin portal.

**Comment by hannesa2** [comment]
> Hi, any updates on this? 3.1.0 is still not available on gradle plugin portal.

Where do you search ?

**Comment by sergejkv** [comment]
https://plugins.gradle.org/plugin/org.jsonschema2dataclass

**Comment by eirnym** [comment]
Yes, it wasn't published. Give me a few days to sort out a few things

**Comment by eirnym** [comment]
logic is moved to `buildSrc`, variable VERSION  removed from workflow
