### ISSUE TITLE
gradle build works once, fails on second attempt

### ISSUE THREAD

**Issue by pgalbraith** [jsonschema2dataclass/js2d-gradle#147]
Not sure if I'm doing something wrong, but here's a simple project to reproduce this behaviour.  "./gradlew build" works on the first run, but fails when run a second time because it cannot find the generated class.

```
/home/paul/projects/generated-sources-error/src/main/java/Test.java:1: error: package schema does not exist
import schema.Action;
             ^
/home/paul/projects/generated-sources-error/src/main/java/Test.java:5: error: cannot find symbol
        System.out.println(Action.VALUE_1);
                           ^
  symbol:   variable Action
  location: class Test
2 errors

FAILURE: Build failed with an exception.

```

[generated-sources-error.zip](https://github.com/jsonschema2dataclass/js2d-gradle/files/6882398/generated-sources-error.zip)

**Comment by eirnym** [comment]
Thank you for an issue, I'll look into it today

**Comment by pgalbraith** [comment]
Inspiration struck me overnight, I bet this is because of the way I'm
specifying the source schema files.  Someone had mentioned this to me here
before, which I promptly forgot about and I didn't take that advice, and I
bet that's the problem :-).  I will update this tonight.

**Comment by pdg-chargelab** [comment]
No it turns out that wasn't the problem.  I changed this:

`source = files("${sourceSets.main.output.resourcesDir}/schema")`

to this instead:

`source.setFrom files("${project.rootDir}/src/main/resources/schema")`

But I still have the same problem, the first gradle build succeeds and subsequent ones fail (until clean/build again).

**Comment by eirnym** [comment]
Thank you for an investigation, I'll add a test for it

**Comment by dtrunk90** [comment]
Same for me with a Spring Boot application.

**Comment by eirnym** [comment]
Upgraded plugin to 3.2.1, still working on the issue
