### ISSUE TITLE
Support for Android Feature along with Application and library

### ISSUE THREAD

**Issue by eirnym** [jsonschema2dataclass/js2d-gradle#200]
Basically the same thing, different place to take attach points from

**Comment by hannesa2** [comment]
Hmm, there is already an Android app and library using it. What's the question exactly ?

Btw, you removed the `androidDev` which used this plugin as code and not like `android` as library

* androidDev: for current development
* android: to test build artifact (from previous release)

**Comment by eirnym** [comment]
Yes, I temporary removed an app to test against previous version. It's worth a while to add them back.

My plan was to add them back with a post-release automatic update if it wasn't a release candidate. What do you think about?

**Comment by eirnym** [comment]
Btw this task became a bit bigger when I discovered proper way to attach to different AGP versions. I have no samples though.

**Comment by eirnym** [comment]
Returning to testing vs demos, I wonder if we can just add last line with `includeBuild` on the fly and get rid of making copies
