### ISSUE TITLE
AGP 3.x sample

### ISSUE THREAD

**Issue by eirnym** [jsonschema2dataclass/js2d-gradle#206]
Android sample uses AGP 3.x is missing. Google releases updates for this branch, so it should be supported. 

Beside sample code, I haven't found  supported by AGP 3.x Gradle version range.

**Comment by hannesa2** [comment]
Who needs this ? Simply don't support AGP 3.x.  Who needs it should put afford into this

**Comment by eirnym** [comment]
makes sense. AGP 4.x needs the same level of support, though :)
