### ISSUE TITLE
Revise demo building

### ISSUE THREAD

**Issue by eirnym** [jsonschema2dataclass/js2d-gradle#214]
Demos should be built when specific folder has been updated (on PR)

Additional info: `lint` task for android apps is failing from time to time

**Comment by hannesa2** [comment]
Why put afford in this ? Demos are build in parallel and you will not save time

**Comment by eirnym** [comment]
there's no need to build a demo, which depends on public release on every PR. More so, all demos depending on other versions of AGP can't be built using `includeBuild` option in `settings.gradle`, or at least as I haven't found a easy way do do it.
