### ISSUE TITLE
how to configure task with kotlin dsl

### ISSUE THREAD

**Issue by gAmUssA** [jsonschema2dataclass/js2d-gradle#219]
hello!
how I can configure task if I use Kotlin DSL to author my buildscript?

```
jsonSchema2Pojo {
    generateBuilders = true
}
```
doesn't work in kotlin.

Thank you

**Comment by eirnym** [comment]
Oh, thank you! this was a serious issue with extension class visibility. Now you have a Kotlin DSL primer and fixed plugin!
