### ISSUE TITLE
Add Kotlin generation support

### ISSUE THREAD

**Issue by eirnym** [jsonschema2dataclass/js2d-gradle#23]
Add Kotlin generation like it's done in https://github.com/niebes/js2p-gradle/tree/kotlin

**Comment by eirnym** [comment]
@hannesa2 would you like to create a PR for this feature?

**Comment by hannesa2** [comment]
I already did it https://github.com/hannesa2/js2p-gradle/tree/KotlinGenerator but they changed too much

**Comment by eirnym** [comment]
What do you think if we force push or add an additional commit could make this PR mergeable to master without loosing the recent changes?

**Comment by hannesa2** [comment]
Here you go https://github.com/eirnym/js2p-gradle/pull/24 it in this repo. That mean, you can change what you want. 
Do git push force, but please use this `git push --force-with-lease ` to avoid unwanted overwrites

**Comment by eirnym** [comment]
Now plugin is written in Kotlin and we can add Kotlin generator as well.

**Comment by eirnym** [comment]
I suppose, I misunderstand this issue.

Kotlin projects are now fully supported. For kotlin generator I'll open a new issue
