### ISSUE TITLE
Release 1.1 is not available on the Gradel portal

### ISSUE THREAD

**Issue by sergeykad** [jsonschema2dataclass/js2d-gradle#30]
Build fails with the following message: `Plugin [id: 'com.github.eirnym.js2p', version: '1.1'] was not found in any of the following sources`

Also, will it be possible to add release notes?

**Comment by eirnym** [comment]
It's true. README is lacking some information on this topic. 

Since plugin became an official one, I published it under another name and old name won't receive any updates.

**Comment by eirnym** [comment]
Yes, release notes are important for this kind of software. I'll add some

**Comment by KengoTODA** [comment]
I searched the plugin portal by the [ID described in the `build.gradle`](https://github.com/eirnym/js2p-gradle/blob/v1.1/build.gradle#L26), but I cannot find it:

https://plugins.gradle.org/search?term=org.jsonschema2pojo

Is it still under the review by the Gradle team? The first release with new ID could take time for a while.

**Comment by eirnym** [comment]
Thank you, it's quite interesting. I'll try to republish it once again

**Comment by eirnym** [comment]
Now it's under a review. I hope it will pass it and I'll get a message about.

**Comment by KengoTODA** [comment]
Or please log-in to the plugin portal, then you may find the reason. In my case, there was a text telling that their review was in progress.

**Comment by eirnym** [comment]
Currently it's pending

**Comment by eirnym** [comment]
It's been approved! https://plugins.gradle.org/plugin/org.jsonschema2pojo

**Comment by hannesa2** [comment]
What can I do, do automate this here https://github.com/eirnym/js2p-gradle/blob/master/.github/workflows/release.yml ?

**Comment by KengoTODA** [comment]
Once approved, coming releases will be published quickly.
Just run [`:publishPlugins task`](https://docs.gradle.org/current/userguide/publishing_gradle_plugins.html) in workflow, then we can automate release process.

**Comment by eirnym** [comment]
I have sad news, release 1.1 won't be in plugins.gradle.com soon

**Comment by eirnym** [comment]
@KengoTODA please, join the discussion https://github.com/joelittlejohn/jsonschema2pojo/issues/1070

**Comment by eirnym** [comment]
I rebranded it to `org.jsonschema2dataclass` and we published it again. https://github.com/jsonschema2dataclass/js2d-gradle/pull/38#issuecomment-787983348

**Comment by eirnym** [comment]
version 1.2.3  is published
 https://plugins.gradle.org/plugin/org.jsonschema2dataclass

**Comment by hannesa2** [comment]
> version 1.2.3 is published
> https://plugins.gradle.org/plugin/org.jsonschema2dataclass

Thank you, I already found it
