### ISSUE TITLE
Plugin coordinates changed 

### ISSUE THREAD

**Issue by donat** [jsonschema2dataclass/js2d-gradle#406]
Version 4.2.3 of https://plugins.gradle.org/plugin/org.jsonschema2dataclass has new coordinates in 4.2.3. The new GAV is `org.jsonschema2dataclass:JsonSchema2DataClass:4.3.0`. You probably want to update this code accordingly:

https://github.com/jsonschema2dataclass/js2d-gradle/blob/main/demo/android/agp7/build.gradle#L10

**Comment by eirnym** [comment]
This is correct, thank you for a heads up on that.

**Comment by eirnym** [comment]
Generated code is always java, it's a limitation of underlying library

Android AGP7 example shows few strange things 
* There's no such problem in `4.2.0`
* Libraries in the example (see `:lib` and `:lib2` gradle modules in the example) correctly attach generated code
* Android Studio shows and attaches generated path correctly, I can view and edit main class
* Kotlin build system doesn't attach generated path to build sources from. I can't say the reason.

As temporary workaround it's possible to use new plugin with AGP7 having Android libraries with java sources and use them in main application.

**Comment by eirnym** [comment]
I found a workaround to fix an issue. It's the same as is used for `protobuf` plugin
