### ISSUE TITLE
Prerelease handling

### ISSUE THREAD

**Issue by eirnym** [jsonschema2dataclass/js2d-gradle#42]
Currently prereleases are not handled at all. we should provide a check to handle in the release action

**Comment by hannesa2** [comment]
Simply ?

```
git tag -a 1.2.2-alpha01 -m "Your text"
git tag -a 1.2.2-beta07 -m "Your text"
git tag -a 1.2.2-rc01 -m "Your text"
```

You can do this https://hub.github.com/hub-release.1.html

But I'm out of ideas about a deeper sense of a pre-release.

**Comment by eirnym** [comment]
Good idea to use it. Also there's a checkbox "pre-release" when you hit "new release" button in UI. GitHub has special handling for that

**Comment by eirnym** [comment]
Currently it's an idea and I doesn't know if we should handle this at all

**Comment by hannesa2** [comment]
Or the switch `-p` is added anyhow on tag-name condition `alpha` or `beta` in this line https://github.com/jsonschema2dataclass/js2d-gradle/blob/c1904268c631343fb2651b3d9db9697964e87901/.github/workflows/release.yml#L37
