### ISSUE TITLE
formatTypeMapping config has no effect

### ISSUE THREAD

**Issue by KirillMakrutin** [jsonschema2dataclass/js2d-gradle#421]
Hi!

I couldn't make _formatTypeMapping_ work - both groovy and kotlin demos don't work. 

Here is what I was trying to achieve (e.g. groovy):
- in _address.json_ I had a new _id_ property: `"id": {
      "type": "integer",
      "format": "int64"
    }`
- in _build.gradle_ I added to _jsonSchema2Pojo_: `formatTypeMapping = ["int64": "java.lang.Long"]` 

Expected output should be _Address.id: Long_, but actual result is always _Address.id: Integer_

I may assume that the issue happens in _Js2dConfig_:
```
    maybeDefaultRaw(
        config.formatTypeMapping.orNull,
        defaultConfig.formatTypeMapping.orNull,
    ) { obj: DefaultGenerationConfig -> obj.formatTypeMapping }
```
where ` config.formatTypeMapping.orNull` returns empty _RegularImmutableMap_, but not null.

A workaround that I chose for now is to explicitly define a type like `"id": {
      "type": "integer",
      "existingJavaType": "Long"
    }`

**Comment by eirnym** [comment]
Thank you for an issue

It's interesting, I'll look into it

**Comment by eirnym** [comment]
@KirillMakrutin  Hi, I created a PR to fix your issue, do you mind to review and check it before I merge?

**Comment by KirillMakrutin** [comment]
> @KirillMakrutin Hi, I created a PR to fix your issue, do you mind to review and check it before I merge?

Sorry, didn't notice your message in time - looks good, thanks!

**Comment by eirnym** [comment]
So I'll release new version soon
