### ISSUE TITLE
configuration cache: Js2pGenerationTask: invocation of 'Task.project' at execution time is unsupported

### ISSUE THREAD

**Issue by vlsi** [jsonschema2dataclass/js2d-gradle#429]
See https://github.com/jsonschema2dataclass/js2d-gradle/blob/f0aa65a21e13ee55e0a79bb150611d9d0861db0a/src/main/kotlin/org/jsonschema2dataclass/js2p/Js2pGenerationTask.kt#L28-L30

Test case:
* `org.gradle.unsafe.configuration-cache=true`
* Gradle 7.4.2

Sample project: https://github.com/sigstore/sigstore-java

**Comment by eirnym** [comment]
Interesting…

It wasn't easy to pass whole configuration object as an input directly, so I passed only name of it. It's worth a while to try it again.

**Comment by eirnym** [comment]
Ok, I done this in the least change possible. Passing tons of configuration items all the time is a nightmare, though

**Comment by vlsi** [comment]
Frankly speaking, I don't understand why so many properties is needed, however, have you considered passing `@Nested` configuration object instead? (e.g. https://docs.gradle.org/current/userguide/custom_gradle_types.html#read_only_managed_nested_properties)

**Comment by eirnym** [comment]
JsonSchema2Pojo requires all of them.

**Comment by eirnym** [comment]
`@Nested` is a nice solution. It's possible to use it at some point. I've tried to revert all changes from this PR and apply it. In my case almost all tests have failed. and I feel that I do more harm than help the situation

**Comment by eirnym** [comment]
Feel free to propose a PR
