### ISSUE TITLE
useTitleAsClassname and useJakartaValidation boolean values are switched

### ISSUE THREAD

**Issue by dmeibusch** [jsonschema2dataclass/js2d-gradle#466]
See:
https://github.com/jsonschema2dataclass/js2d-gradle/blob/5e8167278c27f029f72d58ac6b2e5a12170a5190/src/main/kotlin/org/jsonschema2dataclass/js2p/Js2dConfig.kt#L321

when you configure one you are actually configuring the other. 
Took me hours to work out the strange behaviour as I toggled these values in my build config.

**Comment by eirnym** [comment]
Nice find, thank you!

**Comment by eirnym** [comment]
Fix released in 4.5.0
