### ISSUE TITLE
What is the difference between this and jsonschema2pojo?

### ISSUE THREAD

**Issue by jkerak-skyhook** [jsonschema2dataclass/js2d-gradle#482]
It's not clear from the readme, why would I use this project instead of jsonschema2pojo? what additional features are provided?

**Comment by eirnym** [comment]
Currently it way better handles integration with Gradle 6.0-7.5.1 and beyond and few other plugins like Kotlin and Lombok. Also it is published on the gradle plugin portal.

**Comment by eirnym** [comment]
Everyone is welcome to contribute

**Comment by eirnym** [comment]
@jkerak-skyhook Thank you for noticing this. I've revamped documetation
