### ISSUE TITLE
Document Usage and Configuration

### ISSUE THREAD

**Issue by AlexTrotsenko** [jsonschema2dataclass/js2d-gradle#5]
See [Usage documentation](https://github.com/joelittlejohn/jsonschema2pojo/tree/master/jsonschema2pojo-gradle-plugin#usage) in original plugin repo.

Currently configuration only partially shown in the [example](https://github.com/eirnym/js2p-gradle/blob/aef89d35d8a0e3e0965b46752fc2697522157bd6/example/java/build.gradle#L23) of _build.gradle_.

**Comment by eirnym** [comment]
Thanks, I'll update this repo as soon as possible

**Comment by eirnym** [comment]
@AlexTrotsenko I updated the documentation in #74 

Please, review it and any further help is welcome
