### ISSUE TITLE
Target folder prefix in configuration

### ISSUE THREAD

**Issue by eirnym** [jsonschema2dataclass/js2d-gradle#78]
plugin configurations usually define target folder prefix. Implement if needed

**Comment by eirnym** [comment]
@hannesa2 what do you think on this matter

**Comment by hannesa2** [comment]
For me it's not clear what this is.
When there is something like this

`targetDirectory = file("${project.rootDir}/build/generated-sources/js2p")`

how does is looks like with a `targetFolderPrefix` ?

**Comment by hannesa2** [comment]
Btw, I see it's not working at all

<img width="1046" alt="image" src="https://user-images.githubusercontent.com/3314607/112170072-0dd04980-8bf3-11eb-90a9-a7dbb0d0d02c.png">

**Comment by eirnym** [comment]
@hannesa2 yeah, I've removed it mostly because I don't understand the value of it.

Will it be enough to define `targetDirectoryPrefix` only for the top configuration, or should we define it for each execution?
