### ISSUE TITLE
CI and Java 11 don't find error on Android

### ISSUE THREAD

**Issue by hannesa2** [jsonschema2dataclass/js2d-gradle#89]
https://github.com/jsonschema2dataclass/js2d-gradle/pull/88/checks?check_run_id=2236277886

It's not caused on appearing pull request

```
> Task :js2d-gradle:compileGroovy
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass (file:/home/runner/.gradle/wrapper/dists/gradle-6.8.3-bin/7ykxq50lst7lb7wx1nijpicxn/gradle-6.8.3/lib/groovy-all-1.3-2.5.12.jar) to method java.util.AbstractCollection.hugeCapacity(int)
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

When you see this, a follow up error will be ignored. Java 8 works fine. 
With this a test with java 11 and 15 is pointless. 

Any clue how to get rid of it ?

**Comment by eirnym** [comment]
Currently it's fine. 

This is because gradle uses pretty old groovy. This could be fixed in Gradle 7.0

PS: I'm ok with transition of our plugin to Kotlin.

**Comment by eirnym** [comment]
@hannesa2 What do you think on migration of the whole plugin to Kotlin

**Comment by hannesa2** [comment]
It would be nice, Kotlin is for me the best choice and I never did anything with groovy, but I never did Gradle+Kotlin

**Comment by eirnym** [comment]
With Gradle (in opposite to maven), Kotlin runs good along with java and groovy, so migration could be done small part-by-part in separate PRs without breaking anything 

I think we could start with demos, tests and build files, after this we would be able to transfer groovy core. 

Plugin core has a only one place written with groovy-way magic. this place is the constructor of `JS2PConfig` class, where it just copies defaults, and then copies and convert configuration itself. This is the only part I'm have to search about. 

What do you think about? Could you help me with this transition?

**Comment by hannesa2** [comment]
> What do you think about? Could you help me with this transition?

Nice idea, but I can't promise anything.
See #90
