### ISSUE TITLE
Android Parcelable unused import

### ISSUE THREAD

**Issue by hannesa2** [jsonschema2dataclass/js2d-gradle#9]
It's a copy from https://github.com/joelittlejohn/jsonschema2pojo/issues/1150 (It's confusion where to post an issue)

![image](https://user-images.githubusercontent.com/3314607/90005200-23fa4c80-dc97-11ea-9fd0-5d95af19ab21.png)

How to get rid of this unused imports ?

This is the only place I found, but to be honest, I don't understand what's going on there

https://github.com/joelittlejohn/jsonschema2pojo/blob/98d1e6ab69ba7d9cda851d1dc901e6d2a54062e6/jsonschema2pojo-core/src/main/java/org/jsonschema2pojo/util/ParcelableHelper.java#L52

**Comment by eirnym** [comment]
Thank you, 

I'll review it as soon as possible, and will add support for Android

**Comment by eirnym** [comment]
Thank you for an android example. This is a problem of the underlying library. I'll get notified as well on it.
